# Generated by Django 4.2.1 on 2023-06-18 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cart_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
