# Generated by Django 4.2.1 on 2023-06-19 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_order_cart_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cart_type',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
